[package]
name = "commanders_bin"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
bevy_asset_loader = { workspace = true }
commanders_main_menu = { path = "../commanders_main_menu" }
commanders_global = { path = "../commanders_global" }
